#!/usr/bin/env python3
"""Export a wind-aligned Cape Town city subset as an OpenFOAM 14 case.

The first case intentionally uses flat building roofs and a steady neutral
k-epsilon setup.  It is a reproducible meshing/solver pilot, not yet a
validated atmospheric-boundary-layer model.  Viewer coordinates are rotated
so OpenFOAM +x is always the downwind direction; ``case.json`` records the
inverse transform required to return sampled results to the browser.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import stat
import sys
from typing import Iterable

import numpy as np
import rasterio
from shapely import affinity, constrained_delaunay_triangles
from shapely.geometry import Polygon, box
from shapely.geometry.polygon import orient

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.build_scene import fill_nearest


DEFAULT_SCENE = PROJECT_ROOT / "public/assets/fallback.json"
DEFAULT_MANIFEST = PROJECT_ROOT / "public/assets/manifest.json"
DEFAULT_CANOPY = PROJECT_ROOT / "public/assets/canopy.json"
DEFAULT_OUTPUT = PROJECT_ROOT / "data/openfoam/cases/cbd_se_pilot"
OPENFOAM_BASHRC = Path("/opt/openfoam14/etc/bashrc")

# Street-tree canopy as a porous momentum sink, not a solid. Leaf area density
# (LAD) and drag coefficient are standard parameters in urban-tree CFD
# literature (e.g. Gromke & Ruck; Buccolieri et al.) for the Darcy-Forchheimer
# quadratic (Forchheimer) term f = Cd * LAD; the linear (Darcy/viscous) term
# is left at zero, which is the common simplification since canopy drag at
# typical urban wind speeds is inertia- not viscosity-dominated. These are
# reasonable defaults for a generic street tree, not a measured value for any
# specific mapped crown — treat them as adjustable, not calibrated.
TREE_LEAF_AREA_DENSITY_M2_PER_M3 = 1.5
TREE_DRAG_COEFFICIENT = 0.2


def foam_header(object_name: str, location: str, class_name: str = "dictionary") -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
  OpenFOAM Foundation v14 case generated by Climate Explorer
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       {class_name};
    location    \"{location}\";
    object      {object_name};
}}
// ************************************************************************* //

"""


def triangle_normal(triangle: tuple[tuple[float, float, float], ...]) -> tuple[float, float, float]:
    a, b, c = (np.asarray(point, dtype=float) for point in triangle)
    normal = np.cross(b - a, c - a)
    length = float(np.linalg.norm(normal))
    if length <= 1e-12:
        return 0.0, 0.0, 0.0
    normal /= length
    return tuple(float(value) for value in normal)


def write_ascii_stl(path: Path, name: str, triangles: Iterable[tuple[tuple[float, float, float], ...]]) -> int:
    count = 0
    with path.open("w", encoding="ascii") as stream:
        stream.write(f"solid {name}\n")
        for triangle in triangles:
            normal = triangle_normal(triangle)
            if normal == (0.0, 0.0, 0.0):
                continue
            stream.write(f"  facet normal {normal[0]:.9g} {normal[1]:.9g} {normal[2]:.9g}\n")
            stream.write("    outer loop\n")
            for x, y, z in triangle:
                stream.write(f"      vertex {x:.6f} {y:.6f} {z:.6f}\n")
            stream.write("    endloop\n  endfacet\n")
            count += 1
        stream.write(f"endsolid {name}\n")
    return count


def cancel_duplicate_triangles(triangles):
    """Remove coincident faces and cancel opposite-facing internal faces."""
    groups: dict[tuple[tuple[float, float, float], ...], list] = {}
    for triangle in triangles:
        key = tuple(sorted(tuple(round(value, 6) for value in point) for point in triangle))
        groups.setdefault(key, []).append(triangle)
    cleaned = []
    for matches in groups.values():
        reference = np.asarray(triangle_normal(matches[0]))
        positive = [item for item in matches if np.dot(reference, triangle_normal(item)) >= 0]
        negative = [item for item in matches if np.dot(reference, triangle_normal(item)) < 0]
        if len(positive) > len(negative):
            cleaned.append(positive[0])
        elif len(negative) > len(positive):
            cleaned.append(negative[0])
    return cleaned


def wind_axes(direction_deg: float) -> tuple[tuple[float, float], tuple[float, float]]:
    """Return downwind and crosswind unit vectors in viewer (x, z)."""
    angle = math.radians(direction_deg)
    downwind = (-math.sin(angle), math.cos(angle))
    crosswind = (-downwind[1], downwind[0])
    return downwind, crosswind


def viewer_to_foam(
    x: float,
    z: float,
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
) -> tuple[float, float]:
    relative_x, relative_z = x - center[0], z - center[1]
    return (
        relative_x * downwind[0] + relative_z * downwind[1],
        relative_x * crosswind[0] + relative_z * crosswind[1],
    )


def foam_to_viewer(
    x: float,
    y: float,
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
) -> tuple[float, float]:
    return (
        center[0] + x * downwind[0] + y * crosswind[0],
        center[1] + x * downwind[1] + y * crosswind[1],
    )


def full_scene_domain(
    buildings: list,
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
    upstream_padding: float = 300.0,
    downstream_padding: float = 600.0,
    lateral_padding: float = 300.0,
) -> tuple[float, float, float, float]:
    """Return a wind-aligned domain containing every mapped building."""
    projected = [
        viewer_to_foam(float(x), float(z), center, downwind, crosswind)
        for record in buildings
        for x, z in record[2]
    ]
    if not projected:
        raise ValueError("the scene contains no building vertices")
    xs, ys = zip(*projected)
    return (
        math.floor(min(xs) - upstream_padding),
        math.ceil(max(xs) + downstream_padding),
        math.floor(min(ys) - lateral_padding),
        math.ceil(max(ys) + lateral_padding),
    )


def transformed_polygon(
    ring: list[list[float]],
    holes: list[list[list[float]]],
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
) -> Polygon:
    polygon = Polygon(ring, holes)
    # Shapely affine matrix: x'=a*x+b*y+xoff, y'=d*x+e*y+yoff.
    center_x = center[0] * downwind[0] + center[1] * downwind[1]
    center_y = center[0] * crosswind[0] + center[1] * crosswind[1]
    return affinity.affine_transform(
        polygon,
        [downwind[0], downwind[1], crosswind[0], crosswind[1], -center_x, -center_y],
    )


def polygon_parts(geometry):
    """Yield polygons from Polygon, MultiPolygon or clipped collections."""
    if geometry.is_empty:
        return
    if geometry.geom_type == "Polygon":
        yield geometry
        return
    for part in getattr(geometry, "geoms", ()):
        yield from polygon_parts(part)


def polygon_triangles(polygon: Polygon, elevation: float, upward: bool) -> Iterable[tuple[tuple[float, float, float], ...]]:
    for candidate in constrained_delaunay_triangles(polygon).geoms:
        coordinates = list(candidate.exterior.coords)[:3]
        triangle = tuple((float(x), float(y), elevation) for x, y in coordinates)
        normal = triangle_normal(triangle)
        if (normal[2] > 0) != upward:
            triangle = triangle[0], triangle[2], triangle[1]
        yield triangle


def wall_triangles(polygon: Polygon, bottom: float, top: float) -> Iterable[tuple[tuple[float, float, float], ...]]:
    oriented = orient(polygon, sign=1.0)
    rings = [(oriented.exterior, False), *((ring, True) for ring in oriented.interiors)]
    for ring, hole in rings:
        coordinates = list(ring.coords)
        for (ax, ay), (bx, by) in zip(coordinates, coordinates[1:]):
            if math.hypot(bx - ax, by - ay) < 1e-8:
                continue
            a0, b0 = (ax, ay, bottom), (bx, by, bottom)
            a1, b1 = (ax, ay, top), (bx, by, top)
            if hole:
                yield a0, b1, b0
                yield a0, a1, b1
            else:
                yield a0, b0, b1
                yield a0, b1, a1


def load_canopy_records(canopy_path: Path) -> list[tuple[float, float, list]]:
    """Return (crown_base_y, crown_top_y, rings) for every mapped tree crown.

    ``canopy.json`` format: [source_id, ground_y, crown_base_y, crown_top_y,
    seed, rings], where rings is a list of components and each component is
    either a bare ring (list of [x, y] points) or a ring-with-holes list
    whose first entry is the exterior ring — mirrors the same defensive
    parsing scripts/dem_utils.py::load_cbd_obstacle_fields already uses for
    the screening proxy's canopy drag mask.
    """
    if not canopy_path.exists():
        return []
    data = json.loads(canopy_path.read_text(encoding="utf-8"))
    records = []
    for record in data.get("canopies", []):
        if not record or len(record) < 6:
            continue
        crown_base_y, crown_top_y = float(record[2]), float(record[3])
        for component in record[-1] or []:
            ring = component[0] if component and isinstance(component[0][0], (list, tuple)) else component
            if len(ring) >= 3:
                records.append((crown_base_y, crown_top_y, ring))
    return records


def tree_crown_triangles(
    canopy_path: Path,
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
    datum: float,
    domain_polygon: Polygon,
) -> Iterable[tuple[tuple[float, float, float], ...]]:
    """Yield a closed triangulated solid per tree crown, wind-aligned.

    Each crown becomes its own capped prism (flat top and bottom caps plus
    extruded walls) between its mapped crown-base and crown-top height, the
    same construction buildings already use. A closed solid per crown — not
    one shared surface — is what lets snappyHexMesh mark the cells inside
    each one as belonging to the porous "trees" cellZone via
    ``cellZoneInside inside`` without needing a wall boundary.
    """
    for crown_base_y, crown_top_y, ring in load_canopy_records(canopy_path):
        if crown_top_y <= crown_base_y + 0.5:
            continue
        polygon = transformed_polygon(ring, [], center, downwind, crosswind)
        if not polygon.is_valid:
            polygon = polygon.buffer(0)
        if polygon.is_empty or polygon.area < 1.0 or not polygon.intersects(domain_polygon):
            continue
        clipped = polygon.intersection(domain_polygon.buffer(-0.05))
        for part in polygon_parts(clipped):
            if part.is_empty or part.area < 1.0:
                continue
            part = orient(part, sign=1.0)
            bottom = crown_base_y - datum
            top = crown_top_y - datum
            yield from polygon_triangles(part, bottom, upward=False)
            yield from polygon_triangles(part, top, upward=True)
            yield from wall_triangles(part, bottom, top)


def sample_terrain(
    dtm_path: Path,
    manifest: dict,
    center: tuple[float, float],
    downwind: tuple[float, float],
    crosswind: tuple[float, float],
    domain: tuple[float, float, float, float],
    spacing: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x_min, x_max, y_min, y_max = domain
    columns = max(2, int(math.ceil((x_max - x_min) / spacing)))
    rows = max(2, int(math.ceil((y_max - y_min) / spacing)))
    xs = np.linspace(x_min, x_max, columns + 1)
    ys = np.linspace(y_min, y_max, rows + 1)
    grid_x, grid_y = np.meshgrid(xs, ys)
    viewer_x = center[0] + grid_x * downwind[0] + grid_y * crosswind[0]
    viewer_z = center[1] + grid_x * downwind[1] + grid_y * crosswind[1]
    origin_x, origin_y = (float(value) for value in manifest["origin"])
    absolute_x = origin_x + viewer_x
    absolute_y = origin_y - viewer_z

    with rasterio.open(dtm_path) as source:
        raster = source.read(1, masked=True)
        valid = ~np.ma.getmaskarray(raster)
        values = fill_nearest(raster.filled(0.0).astype(np.float32), valid)
        row_index, column_index = rasterio.transform.rowcol(source.transform, absolute_x, absolute_y)
        row_index = np.clip(np.asarray(row_index).reshape(absolute_x.shape), 0, values.shape[0] - 1)
        column_index = np.clip(np.asarray(column_index).reshape(absolute_x.shape), 0, values.shape[1] - 1)
        heights = values[row_index, column_index].astype(float)
    return xs, ys, heights


def terrain_triangles(xs: np.ndarray, ys: np.ndarray, heights: np.ndarray, datum: float):
    for row in range(len(ys) - 1):
        for column in range(len(xs) - 1):
            p00 = (float(xs[column]), float(ys[row]), float(heights[row, column] - datum))
            p10 = (float(xs[column + 1]), float(ys[row]), float(heights[row, column + 1] - datum))
            p01 = (float(xs[column]), float(ys[row + 1]), float(heights[row + 1, column] - datum))
            p11 = (float(xs[column + 1]), float(ys[row + 1]), float(heights[row + 1, column + 1] - datum))
            yield p00, p10, p11
            yield p00, p11, p01


def write_case_files(
    case_dir: Path,
    domain: tuple[float, float, float, float],
    z_max: float,
    base_cell: float,
    speed: float,
    inside_point: tuple[float, float, float],
    core_half: float,
    include_trees: bool = False,
) -> None:
    x_min, x_max, y_min, y_max = domain
    x_cells = max(4, int(math.ceil((x_max - x_min) / base_cell)))
    y_cells = max(4, int(math.ceil((y_max - y_min) / base_cell)))
    z_cells = max(4, int(math.ceil(z_max / base_cell)))
    k_value = 1.5 * (0.1 * speed) ** 2
    epsilon = 0.09 ** 0.75 * k_value ** 1.5 / 30.0

    # Trees are a porous cellZone, not a wall: refined like buildings/terrain
    # but with cellZoneInside + faceType internal so snappyHexMesh tags the
    # enclosed cells without adding a solid boundary — air still flows
    # through, fvModels below applies the momentum sink on that cellZone.
    trees_geometry = '    trees { type triSurface; file "trees.stl"; }\n' if include_trees else ""
    trees_refinement = (
        "        trees { level (0 0); faceZone treesFaces; cellZone trees; "
        "cellZoneInside inside; faceType internal; }\n"
    ) if include_trees else ""
    trees_surface_check = (
        "runApplication -s trees surfaceCheck constant/triSurface/trees.stl\n"
    ) if include_trees else ""

    files: dict[str, str] = {}
    files["system/blockMeshDict"] = foam_header("blockMeshDict", "system") + f"""vertices
(
    ({x_min} {y_min} 0) ({x_max} {y_min} 0) ({x_max} {y_max} 0) ({x_min} {y_max} 0)
    ({x_min} {y_min} {z_max}) ({x_max} {y_min} {z_max}) ({x_max} {y_max} {z_max}) ({x_min} {y_max} {z_max})
);
blocks
(
    hex (0 1 2 3 4 5 6 7) ({x_cells} {y_cells} {z_cells}) simpleGrading (1 1 1)
);
boundary
(
    inlet {{ type patch; faces ((0 3 7 4)); }}
    outlet {{ type patch; faces ((1 5 6 2)); }}
    ground {{ type wall; faces ((0 1 2 3)); }}
    sidesAndTop {{ type symmetry; faces ((0 4 5 1) (3 2 6 7) (4 7 6 5)); }}
);
"""
    files["system/surfaceFeaturesDict"] = foam_header("surfaceFeaturesDict", "system") + """surfaces ("buildings.stl" "terrain.stl");
#includeEtc "caseDicts/surface/surfaceFeaturesDict.cfg"
"""
    files["system/meshQualityDict"] = foam_header("meshQualityDict", "system") + """#includeEtc "caseDicts/mesh/generation/meshQualityDict.cfg"
"""
    files["system/snappyHexMeshDict"] = foam_header("snappyHexMeshDict", "system") + f"""#includeEtc "caseDicts/mesh/generation/snappyHexMeshDict.cfg"

castellatedMesh on;
snap            on;
addLayers       off;

geometry
{{
    buildings {{ type triSurface; file "buildings.stl"; }}
    terrain {{ type triSurface; file "terrain.stl"; }}
{trees_geometry}    pedestrianRefinement
    {{
        type box;
        min ({-core_half:.3f} {-core_half:.3f} 0);
        max ({core_half:.3f} {core_half:.3f} 35);
    }}
}}

castellatedMeshControls
{{
    maxLocalCells 3000000;
    maxGlobalCells 5000000;
    minRefinementCells 0;
    nCellsBetweenLevels 3;
    features
    (
        {{ file "buildings.eMesh"; level 1; }}
        {{ file "terrain.eMesh"; level 1; }}
    );
    refinementSurfaces
    {{
        buildings {{ level (2 2); patchInfo {{ type wall; }} }}
        terrain {{ level (1 1); patchInfo {{ type wall; }} }}
{trees_refinement}    }}
    refinementRegions
    {{
        pedestrianRefinement {{ mode inside; level 1; }}
    }}
    resolveFeatureAngle 30;
    insidePoint ({inside_point[0]:.6f} {inside_point[1]:.6f} {inside_point[2]:.6f});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch 5;
    tolerance 2.0;
    nSolveIter 60;
    nRelaxIter 8;
    explicitFeatureSnap true;
    implicitFeatureSnap false;
}}
addLayersControls {{ layers {{}} }}
meshQualityControls
{{
    #include "meshQualityDict"
    maxBoundarySkewness 4;
    maxInternalSkewness 4;
    minDeterminant 0.001;
}}
writeFlags (scalarLevels);
mergeTolerance 1e-6;
"""
    files["system/controlDict"] = foam_header("controlDict", "system") + """solver          incompressibleFluid;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         500;
deltaT          1;
writeControl    timeStep;
writeInterval   100;
writeFormat     binary;
writePrecision  7;
writeCompression off;
runTimeModifiable true;
"""
    files["system/fvSchemes"] = foam_header("fvSchemes", "system") + """ddtSchemes { default steadyState; }
gradSchemes
{
    default Gauss linear;
    limited cellLimited Gauss linear 1;
    grad(U) $limited;
    grad(k) $limited;
    grad(epsilon) $limited;
}
divSchemes
{
    default none;
    div(phi,U) bounded Gauss linearUpwind limited;
    turbulence bounded Gauss limitedLinear 1;
    div(phi,k) $turbulence;
    div(phi,epsilon) $turbulence;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
wallDist { method meshWave; }
"""
    files["system/fvSolution"] = foam_header("fvSolution", "system") + """solvers
{
    p { solver GAMG; smoother GaussSeidel; tolerance 1e-6; relTol 0.1; }
    Phi { $p; }
    "(U|k|epsilon)" { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-6; relTol 0.1; }
}
SIMPLE
{
    residualControl { p 1e-4; U 1e-4; "(k|epsilon)" 1e-4; }
    nNonOrthogonalCorrectors 0;
    pRefCell 0;
    pRefValue 0;
}
potentialFlow { nNonOrthogonalCorrectors 10; }
relaxationFactors
{
    fields { p 0.3; }
    equations { U 0.7; "(k|epsilon).*" 0.7; }
}
"""
    files["system/functions"] = foam_header("functions", "system")
    files["system/decomposeParDict"] = foam_header("decomposeParDict", "system") + """numberOfSubdomains 4;
method scotch;
"""
    files["constant/physicalProperties"] = foam_header("physicalProperties", "constant") + """viscosityModel constant;
nu 1.5e-05;
"""
    files["constant/momentumTransport"] = foam_header("momentumTransport", "constant") + """simulationType RAS;
RAS
{
    model kEpsilon;
    turbulence on;
}
"""
    files["0/U"] = foam_header("U", "0", "volVectorField") + f"""Uinlet ({speed:.6f} 0 0);
dimensions [velocity];
internalField uniform $Uinlet;
boundaryField
{{
    inlet {{ type fixedValue; value uniform $Uinlet; }}
    outlet {{ type pressureInletOutletVelocity; value uniform $Uinlet; }}
    wall {{ type noSlip; }}
    #includeEtc "caseDicts/setConstraintTypes"
}}
"""
    files["0/p"] = foam_header("p", "0", "volScalarField") + """dimensions [kinematicPressure];
internalField uniform 0;
boundaryField
{
    inlet { type zeroGradient; }
    outlet { type totalPressure; p0 uniform 0; value uniform 0; }
    wall { type zeroGradient; }
    #includeEtc "caseDicts/setConstraintTypes"
}
"""
    files["0/k"] = foam_header("k", "0", "volScalarField") + f"""kInlet {k_value:.8g};
dimensions [turbulentKineticEnergy];
internalField uniform $kInlet;
boundaryField
{{
    inlet {{ type fixedValue; value uniform $kInlet; }}
    outlet {{ type inletOutlet; inletValue uniform $kInlet; value uniform $kInlet; }}
    wall {{ type kqRWallFunction; value uniform $kInlet; }}
    #includeEtc "caseDicts/setConstraintTypes"
}}
"""
    files["0/epsilon"] = foam_header("epsilon", "0", "volScalarField") + f"""epsilonInlet {epsilon:.8g};
dimensions [turbulentEpsilon];
internalField uniform $epsilonInlet;
boundaryField
{{
    inlet {{ type fixedValue; value uniform $epsilonInlet; }}
    outlet {{ type inletOutlet; inletValue uniform $epsilonInlet; value uniform $epsilonInlet; }}
    wall {{ type epsilonWallFunction; value uniform $epsilonInlet; }}
    #includeEtc "caseDicts/setConstraintTypes"
}}
"""
    files["0/nut"] = foam_header("nut", "0", "volScalarField") + """dimensions [turbulentViscosity];
internalField uniform 0;
boundaryField
{
    inlet { type calculated; value uniform 0; }
    outlet { type calculated; value uniform 0; }
    wall { type nutkWallFunction; value uniform 0; }
    #includeEtc "caseDicts/setConstraintTypes"
}
"""
    if include_trees:
        forchheimer_f = TREE_DRAG_COEFFICIENT * TREE_LEAF_AREA_DENSITY_M2_PER_M3
        files["constant/coordinateSystems"] = foam_header("coordinateSystems", "constant") + """trees
{
    type    cartesian;
    origin  (0 0 0);
    coordinateRotation
    {
        type    axesRotation;
        e1  (1 0 0);
        e2  (0 1 0);
    }
}
"""
        files["constant/fvModels"] = foam_header("fvModels", "constant") + f"""// Isotropic Darcy-Forchheimer sink over the "trees" cellZone (see
// snappyHexMeshDict's refinementSurfaces): d is left at zero (viscous term
// negligible at urban wind speeds), f = Cd * LAD is the standard urban-tree
// canopy parameterisation. See TREE_LEAF_AREA_DENSITY_M2_PER_M3 and
// TREE_DRAG_COEFFICIENT in scripts/export_openfoam_case.py for the source
// values and their literature basis.
porosity
{{
    type            porosityForce;

    porosityForce
    {{
        cellZone        trees;
        type            DarcyForchheimer;

        d   (0 0 0);
        f   ({forchheimer_f:.4f} {forchheimer_f:.4f} {forchheimer_f:.4f});

        coordinateSystem trees;
    }}
}}
"""
    for relative, content in files.items():
        destination = case_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")

    allmesh = case_dir / "Allmesh"
    allmesh.write_text(f"""#!/bin/bash
set -e
. {OPENFOAM_BASHRC}
cd \"$(dirname \"$0\")\"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
foamCleanCase
runApplication -s buildings surfaceCheck constant/triSurface/buildings.stl
runApplication -s terrain surfaceCheck constant/triSurface/terrain.stl
{trees_surface_check}runApplication surfaceFeatures
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication -s standard checkMesh
grep -q "Mesh OK" log.checkMesh.standard || {{ echo "Standard checkMesh failed"; exit 1; }}
runApplication -s exhaustive checkMesh -allGeometry -allTopology
""", encoding="utf-8")
    allrun = case_dir / "Allrun"
    allrun.write_text(f"""#!/bin/bash
set -e
. {OPENFOAM_BASHRC}
cd \"$(dirname \"$0\")\"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
if [ ! -d constant/polyMesh ]; then ./Allmesh; fi
latest_time="$(foamListTimes -latestTime 2>/dev/null || true)"
if [ -z "$latest_time" ] || [ "$latest_time" = "0" ]; then
    runApplication -o potentialFoam -writePhi
fi
nprocs="${{OPENFOAM_NPROCS:-4}}"
if [ "$nprocs" -gt 1 ]; then
    foamDictionary system/decomposeParDict -entry numberOfSubdomains -set "$nprocs"
    decomposePar -latestTime -force > log.decomposePar 2>&1
    mpirun -np "$nprocs" foamRun -parallel > log.foamRun 2>&1
    reconstructPar -latestTime > log.reconstructPar 2>&1
else
    runApplication -o foamRun
fi
""", encoding="utf-8")
    allpost = case_dir / "Allpost"
    allpost.write_text(f"""#!/bin/bash
set -e
. {OPENFOAM_BASHRC}
cd \"$(dirname \"$0\")\"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
runApplication -o foamToVTK -latestTime -fields '(U p k epsilon)'
""", encoding="utf-8")
    for executable in (allmesh, allrun, allpost):
        executable.chmod(executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scene", type=Path, default=DEFAULT_SCENE)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--center-x", type=float, default=0.0)
    parser.add_argument("--center-z", type=float, default=0.0)
    parser.add_argument("--direction-deg", type=float, default=135.0)
    parser.add_argument("--speed-mps", type=float, default=10.0)
    parser.add_argument("--analysis-size-m", type=float, default=250.0)
    parser.add_argument("--upstream-m", type=float, default=250.0)
    parser.add_argument("--downstream-m", type=float, default=450.0)
    parser.add_argument("--lateral-m", type=float, default=300.0)
    parser.add_argument("--top-m", type=float, default=180.0)
    parser.add_argument("--base-cell-m", type=float, default=12.0)
    parser.add_argument("--terrain-spacing-m", type=float, default=8.0)
    parser.add_argument("--full-scene", action="store_true",
                        help="derive a padded domain containing every building in the scene")
    parser.add_argument("--include-trees", action="store_true",
                        help="mesh mapped tree canopy as a porous cellZone (Darcy-Forchheimer momentum sink)")
    parser.add_argument("--canopy", type=Path, default=DEFAULT_CANOPY)
    parser.add_argument("--openfoam-bashrc", type=Path, default=OPENFOAM_BASHRC)
    args = parser.parse_args()
    if not args.openfoam_bashrc.exists():
        parser.error(f"OpenFOAM environment not found: {args.openfoam_bashrc}")
    if args.speed_mps <= 0 or args.analysis_size_m <= 0 or args.base_cell_m <= 0:
        parser.error("speed, analysis size and base cell size must be positive")

    scene = json.loads(args.scene.read_text(encoding="utf-8"))
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    dtm_path = PROJECT_ROOT / manifest["layers"]["terrain"]["source"]
    center = (args.center_x, args.center_z)
    downwind, crosswind = wind_axes(args.direction_deg)
    domain = full_scene_domain(scene["buildings"], center, downwind, crosswind) if args.full_scene else (
        -args.upstream_m, args.downstream_m, -args.lateral_m, args.lateral_m,
    )
    xs, ys, terrain = sample_terrain(
        dtm_path, manifest, center, downwind, crosswind, domain, args.terrain_spacing_m,
    )
    datum = math.floor(float(np.min(terrain))) - 2.0
    core_half = args.analysis_size_m * math.sqrt(2) * 0.5
    domain_polygon = box(domain[0], domain[2], domain[1], domain[3])

    building_triangles = []
    building_count = 0
    maximum_roof = 0.0
    for record in scene["buildings"]:
        ground, height, ring = float(record[0]), float(record[1]), record[2]
        holes = record[13] or [] if len(record) > 13 else []
        minimum_height = float(record[10] or 0.0) if len(record) > 10 else 0.0
        polygon = transformed_polygon(ring, holes, center, downwind, crosswind)
        if not polygon.is_valid:
            polygon = polygon.buffer(0)
        if polygon.is_empty or not polygon.intersects(domain_polygon):
            continue
        clipped = polygon.intersection(domain_polygon.buffer(-0.05))
        for part in polygon_parts(clipped):
            if part.is_empty or part.area < 2.0:
                continue
            part = orient(part, sign=1.0)
            bottom = ground + minimum_height - datum - (0.5 if minimum_height <= 0 else 0.0)
            top = ground + height - datum
            if top <= bottom + 0.5:
                continue
            building_triangles.extend(polygon_triangles(part, bottom, upward=False))
            building_triangles.extend(polygon_triangles(part, top, upward=True))
            building_triangles.extend(wall_triangles(part, bottom, top))
            building_count += 1
            maximum_roof = max(maximum_roof, top)

    case_dir = args.output.resolve()
    tri_surface = case_dir / "constant/triSurface"
    tri_surface.mkdir(parents=True, exist_ok=True)
    raw_building_triangle_count = len(building_triangles)
    building_triangles = cancel_duplicate_triangles(building_triangles)
    building_triangle_count = write_ascii_stl(tri_surface / "buildings.stl", "buildings", building_triangles)
    terrain_triangle_count = write_ascii_stl(
        tri_surface / "terrain.stl", "terrain", terrain_triangles(xs, ys, terrain, datum),
    )
    tree_triangle_count = 0
    if args.include_trees:
        tree_triangles = cancel_duplicate_triangles(list(
            tree_crown_triangles(args.canopy, center, downwind, crosswind, datum, domain_polygon),
        ))
        tree_triangle_count = write_ascii_stl(tri_surface / "trees.stl", "trees", tree_triangles)
        if tree_triangle_count == 0:
            parser.error(f"--include-trees was set but no canopy geometry fell inside the domain (checked {args.canopy})")
    z_max = max(args.top_m, maximum_roof + 50.0, float(np.max(terrain) - datum) + 100.0)
    inlet_ground = float(np.median(terrain[:, 0]) - datum)
    inside_point = (domain[0] + args.base_cell_m * 0.75, 0.0, inlet_ground + args.base_cell_m)
    write_case_files(
        case_dir, domain, z_max, args.base_cell_m, args.speed_mps, inside_point, core_half,
        include_trees=args.include_trees,
    )

    metadata = {
        "schema": "climate-explorer-openfoam-case/1",
        "case_id": case_dir.name,
        "openfoam_distribution": "Foundation",
        "openfoam_version": 14,
        "validation_status": "exploratory_unvalidated_pilot",
        "model": "steady incompressible RANS k-epsilon; uniform neutral inlet",
        "viewer_center": list(center),
        "direction_deg_from": args.direction_deg,
        "reference_speed_mps": args.speed_mps,
        "foam_axes_in_viewer_xz": {"x_downwind": list(downwind), "y_crosswind": list(crosswind)},
        "vertical_datum_m": datum,
        "domain_foam_m": {"x": [domain[0], domain[1]], "y": [domain[2], domain[3]], "z": [0.0, z_max]},
        "analysis_size_m": args.analysis_size_m,
        "base_cell_m": args.base_cell_m,
        "terrain_spacing_m": args.terrain_spacing_m,
        "full_scene": args.full_scene,
        "source_building_records": len(scene["buildings"]),
        "building_parts": building_count,
        "raw_building_triangles": raw_building_triangle_count,
        "building_triangles": building_triangle_count,
        "terrain_triangles": terrain_triangle_count,
        "trees": {
            "included": args.include_trees,
            "tree_triangles": tree_triangle_count,
            "leaf_area_density_m2_per_m3": TREE_LEAF_AREA_DENSITY_M2_PER_M3,
            "drag_coefficient": TREE_DRAG_COEFFICIENT,
        } if args.include_trees else {"included": False},
        "limitations": [
            "flat roof envelopes; detailed roof_surface.bin is not yet exported",
            "uniform inlet pilot, not a validated atmospheric boundary layer",
        ] + ([] if args.include_trees else ["trees are not represented in this case"]),
    }
    (case_dir / "case.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metadata, indent=2))
    print(f"\nGenerated {case_dir}")
    print(f"Mesh only: {case_dir / 'Allmesh'}")
    print(f"Mesh + solve: {case_dir / 'Allrun'}")
    print(f"Latest result to VTK: {case_dir / 'Allpost'}")


if __name__ == "__main__":
    main()
